# Generated by Django 5.0.4 on 2024-04-30 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reminderBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminderDescription', models.CharField(max_length=250)),
                ('reminderDetails', models.TextField(max_length=1000)),
                ('reminderCreationTime', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='reminderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminderDueDateStart', models.DateTimeField()),
                ('reminderDueDateEnd', models.DateTimeField()),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reminders.reminderbase')),
            ],
        ),
    ]
