# Generated by Django 5.0.4 on 2024-05-03 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='reminderBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminderDescription', models.CharField(max_length=250)),
                ('reminderCreationTime', models.DateTimeField(auto_now_add=True, verbose_name='date published')),
                ('reminderDetails', models.TextField(default='', max_length=1000)),
                ('reminderDueDateStart', models.DateTimeField(blank=True, null=True)),
                ('reminderDueDateEnd', models.DateTimeField(blank=True, null=True)),
                ('reminderImportance', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=1)),
                ('reminderCompletion', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
            ],
        ),
    ]
