# Generated by Django 5.0.4 on 2024-04-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reminderBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminderDescription', models.CharField(max_length=250)),
                ('reminderCreationTime', models.DateTimeField(verbose_name='date published')),
                ('reminderDetails', models.TextField(default='', max_length=1000)),
                ('reminderDueDateStart', models.DateTimeField(null=True)),
                ('reminderDueDateEnd', models.DateTimeField(null=True)),
            ],
        ),
    ]
