# Generated by Django 5.0.4 on 2024-05-03 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminderbase',
            name='reminderCompletion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reminderbase',
            name='reminderImportance',
            field=models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Critical')], default=1),
        ),
        migrations.AlterField(
            model_name='reminderbase',
            name='reminderDueDateEnd',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reminderbase',
            name='reminderDueDateStart',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
